### ISSUE TITLE
Word2Vec Embeddings

### ISSUE THREAD

**Issue by fishjh2** [easonnie/ResEncoder#1]
Hi, 

Have tried to reproduce your result, but found I got marginally worse performance when I used the downloaded version of the Word2Vec as opposed to the embeddings in the saved_embeds.pt file you provide. Have the embeddings in saved_embeds.pt been finetuned already, or initialized in a significant way (I noticed there are no zero rows for words not in the word2vec vocab)?

Many thanks!

**Comment by easonnie** [comment]
saved_embeds.pt is initialized with original Glove embedding. Words not in Glove embedding are randomly initialized (I forgot the actual initialization strategy, it might be the averaging of all In-Vocabulary embedding with slight or no perturbation). You could check the embeddings for all In-Vocabulary Glove words.

My empirical results show that even if you randomly initialized all word embeddings you could still get roughly the same result with more training time. The Glove embedding will only accelerate the training process. That said, minor changes might lead to performance gap.

**Comment by fishjh2** [comment]
Ok many thanks
